version: "3.9"
networks:
  GoodOnions:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/24
         
services:
  cass1:
    image: cassandra
    container_name: cass1
    hostname: cass1
    mem_limit: 2g  
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      GoodOnions:
        ipv4_address: 10.0.1.2
    volumes:
      - ./cass1/dataDB:/var/lib/cassandra    
      - ./cass1/etc:/etc/cassandra   # Use your own config files for full control
    environment: &environment    # Declare and save environments variables into "environment"
        CASSANDRA_SEEDS: "cass1,cass2"    # The first two nodes will be seeds
        CASSANDRA_CLUSTER_NAME: GoodOnions
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128

  cass2:
    image: cassandra
    container_name: cass2
    hostname: cass2
    mem_limit: 2g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      GoodOnions:
        ipv4_address: 10.0.1.3
    volumes:
      - ./cass2/dataDB:/var/lib/cassandra    # This is the volume that will persist data for cass2 node
      - ./cass2/etc:/etc/cassandra    # Use your own config files for full control
    environment: *environment    # point to "environment" to use the same environment variables as cass1
    depends_on:
      cass1:    # start cass2 only after cass1 is healthy
        condition: service_healthy

  cass3:
    image: cassandra
    container_name: cass3
    hostname: cass3
    mem_limit: 2g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      GoodOnions:
        ipv4_address: 10.0.1.4
    volumes:
      - ./cass3/dataDB:/var/lib/cassandra    # This is the volume that will persist data for cass3 node
      - ./cass3/etc:/etc/cassandra    # Use your own config files for full control
    environment: *environment    # point to "environment" to use the same environment variables as cass1
    depends_on:
      cass2:    # start cass3 only after cass1 is healthy
        condition: service_healthy # cass3 only after cass2